# Generated by Django 3.2.6 on 2021-09-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('backInStock', models.BooleanField(default=False)),
                ('inStock', models.BooleanField(default=False)),
                ('discount', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='supermartapp.category')),
            ],
        ),
    ]
