# Generated by Django 3.2.6 on 2021-09-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
