# Generated by Django 3.2.6 on 2021-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0003_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offerPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_benefit',
            field=models.IntegerField(default=0),
        ),
    ]
