# Generated by Django 3.2.6 on 2021-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0005_alter_product_offerpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offerPercentage',
            field=models.TextField(default=0),
        ),
    ]
