# Generated by Django 3.2.6 on 2021-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0009_auto_20211007_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=55)),
                ('decription', models.CharField(max_length=500)),
            ],
        ),
    ]
