# Generated by Django 3.2.6 on 2021-10-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0010_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='decription',
            new_name='description',
        ),
    ]
