# Generated by Django 3.2.6 on 2021-10-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermartapp', '0011_rename_decription_feedback_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
